
	' Reset machine on BREAK
	on brk goto 1000

	' Poke in the ML code
	read a, b
	for i = a to b
		read d
		poke i, d
	next i

	' Define ML functions
	def usr0 = peek(&h1000) * 256 + peek(&h1001)
	def usr1 = peek(&h1002) * 256 + peek(&h1003)
	def usr2 = peek(&h1004) * 256 + peek(&h1005)
	def usr3 = peek(&h1006) * 256 + peek(&h1007)

	' Call ML functions
	a = usr0(299.6)		' Multiply by 2
	b = usr1(299.1)		' Divide by 2
	c = usr2("Testing")	' Number of vowels in string
	d = usr2(0)		' Wrong data type
	e = usr2("")		' Zero length string
	s$ = usr3(0)		' Generate string based on numeric argument

	' Did it work?
	print a  ' 598
	print b  ' 149
	print c  ' 2
	print d  ' 0
	print e  ' 0
	print s$ ' ZERO

	' Wait for BREAK to be pressed
10	goto 10

	' Reset the machine
1000	poke &H71, 0
	exec &H8c1b

	' These included DATA statements are generated by compiling usr.asm
	include "usr.dat"

